filter:
    excluded_paths:
        - 'bin/*'
        - 'public/vendor/*'
        - '*.min.js'
checks:
    php: true
    javascript: true
build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: [php-scrutinizer-run]
