index:
    path: /
    controller: App\Controller\DefaultController::index
login:
    path: /login
    controller: App\Controller\UserController::login
login_check:
    path: /login-check
logout:
    path: /logout
files:
    path: /h
    controller: App\Controller\DefaultController::files
show_file:
    path: /h/{file}
    controller: App\Controller\DefaultController::showRawFile
    requirements:
        file: .+
connector:
    path: /connector
    controller: App\Controller\DefaultController::connector

setup:
    path: /setup
    controller: App\Controller\SetupController::setup
